### ISSUE TITLE
Quanto controle de qualidade metodológico de fato ocorre em bancas e comitês de ética?

### ISSUE THREAD

**Issue by lubianat** [No-Budget-Science/projetos#72]
Comitês de ética em pesquisa são uma fonte interessante de revisão metodológica antes de um projeto de pesquisa, mas esta tarefa não é vista unanimemente como uma atribuição dos mesmos. Dito isso, há CEPs e CEUAs que cobram medidas para garantir rigor metodológico, como cálculos de tamanho amostra, randomização de participantes ou cegamento de experimentadores. Há pouquíssima evidência, porém, sobre o que diferentes comitês de ética em pesquisa cobram dos pesquisadores ao redor do Brasil, e levantar esses dados seria bastante interessante para gerar uma discussão sobre o tema, inclusive dentro dos próprios comitês.

**Comment by olavoamaral** [comment]
Comitês de ética em pesquisa são uma fonte interessante de revisão metodológica antes de um projeto de pesquisa, mas esta tarefa não é vista unanimemente como uma atribuição dos mesmos. Dito isso, há CEPs e CEUAs que cobram medidas para garantir rigor metodológico, como cálculos de tamanho amostra, randomização de participantes ou cegamento de experimentadores. Há pouquíssima evidência, porém, sobre o que diferentes comitês de ética em pesquisa cobram dos pesquisadores ao redor do Brasil, e levantar esses dados seria bastante interessante para gerar uma discussão sobre o tema, inclusive dentro dos próprios comitês.

**Comment by olavoamaral** [comment]
Como um update, estamos começando a montar um instrumento pra fazer isso nas CEUAs brasileiras através dos projetos submetidos à Iniciativa Brasileira de Reprodutibilidade.

**Comment by olavoamaral** [comment]
Fechado porque se sobrepunha quase completamente com o projeto #39
